### ISSUE TITLE
Should a folder with high coverage have the same state as the worst child?

### ISSUE THREAD

**Issue by tenninebt** [tenninebt/vscode-koverage#11]
Now, a folder with a high coverage is green even though there are files with very low coverage inside. That seems a bit confusing even especially for complex hierarchies.
Suggestions :
- Offer filters to be able to see all the low/medium coverage files (Probably worth implementing in any case)
- Make it have the same state as the worst file. 
- Avoid showing a percentage on the folders to avoid the confusion.

Any thoughts?

**Comment by polortiz4** [comment]
If I may comment as a user:
Please don't hide the percentage on the folders, it provides very useful information.
I understand your concern over a folder's green status being misinterpreted as "all my subfolders and files have green status". However, why couldn't you extend the argument to files and say "let's not have the file be green unless _all_ methods inside it pass the threshold". 
My opinion is that in the same way that a file can be green even if there is a method that is not tested, a folder can be green even if a subfile is not green.
Maybe you could have the folder be green but have a "!" next to it, such that if you hover to it, or click it, it says there are non-green methods inside. Or have some other form of differentiating "all subcomponents pass the threshold" vs "the folder as a whole passes the threshold, but not all of the subcomponents do" vs "the folder fails the threshold".
 
(I personally set the green threshold to 100%, so this isn't an issue I've had, really XD)
