### ISSUE TITLE
added ability to exclude code coverage paths from coverage

### ISSUE THREAD

**Issue by default-writer** [tenninebt/vscode-koverage#25]
I got a rexo + live unit tests working in C, but, it is guts to make to ignore completely src/rexo folder, which is actually a git submodule and i do not need to cover it (it is project dependencies)

![image](https://user-images.githubusercontent.com/383256/207549953-1e92f5f4-aee3-4534-a559-09c9f3b76fe7.png)

https://github.com/default-writer/c

**Comment by default-writer** [comment]
after the fix

![image](https://user-images.githubusercontent.com/383256/207588014-da114040-39c6-4a8f-b044-3ea044ac431c.png)

**Comment by default-writer** [comment]
@tenninebt Hi! please take a look, i made some improvements to work with, thanks!

**Comment by tenninebt** [comment]
Closing as per comment : https://github.com/tenninebt/vscode-koverage/pull/26#issuecomment-1351626540
