### ISSUE TITLE
Incorrect usage of @cvrg-report/jacoco-json

### ISSUE THREAD

**Issue by GV94** [tenninebt/vscode-koverage#33]
When trying to get koverage extension to work with my java project, for which we use JaCoCo for coverage reports, I kept getting the following error `[1681454235335][coverageparser][jacoco-parse]: Error: filename: [path-to-coverage-report]/jacoco.xml E.parseContent.parseContent is not a function`

After some investigation, it seems that the usage of `@cvrg-report/jacoco-json` is incorrect.

The [signature of `parseContent` from `@cvrg-report/jacoco-json`](https://github.com/coverage-report/jacoco-json/blob/6acdc345a196057b58119535f34416795354abe5/src/index.js#L93) is `parseContent(xml)` and it returns a promise. However it is being used with the following signature `parseContent(xml, callback)` and does not handle the returned promise.

The following piece of code [(link)](https://github.com/tenninebt/vscode-koverage/blob/148e68d6067ff46caf51013c40245ce1c919cf8b/src/coverage-parser.ts#L128)
```ts
  import { parseContent as jacocoJson } from "@cvrg-report/jacoco-json"
  // ...
  try {
    jacocoJson.parseContent(xmlFile, (err: any, data: any[]) => {
      checkError(err)
      const sections = this.convertSectionsToMap(workspaceFolder, filename, data)
      resolve(sections)
    })
  } catch (error) {
    checkError(error)
  }
```

should probably look something like this
```ts
  import jacocoJson from "@cvrg-report/jacoco-json"

  // ...

  jacocoJson.parseContent(xmlFile)
  .then((data: any[]) => {
    const sections = this.convertSectionsToMap(workspaceFolder, filename, data)
    resolve(sections)
  })
 .catch((err: any) => { 
      checkError(err) 
  })
```

it also seems to me that `xmlExtractCobertura` is broken in the same way as `xmlExtractJacoco`.

**Comment by FieteO** [comment]
I face the same issue. The extension log output is
```json
{
  "label": "Koverage",
  "level": "error",
  "message": "[1691492681965][coverageparser][jacoco-parse]: Error: filename: /home/ubuntu/Downloads/someproject/target/site/jacoco-ut/jacoco.xml E.parseContent.parseContent is not a function\nTypeError: filename: /home/ubuntu/Downloads/someproject/target/site/jacoco-ut/jacoco.xml E.parseContent.parseContent is not a function\n\tat /home/ubuntu/.vscode-server/extensions/tenninebt.vscode-koverage-0.0.14/dist/extension.js:2:626276\n\tat new Promise (<anonymous>)\n\tat /home/ubuntu/.vscode-server/extensions/tenninebt.vscode-koverage-0.0.14/dist/extension.js:2:626135\n\tat Generator.next (<anonymous>)\n\tat j (/home/ubuntu/.vscode-server/extensions/tenninebt.vscode-koverage-0.0.14/dist/extension.js:2:623364)\n\tat s (/home/ubuntu/.vscode-server/extensions/tenninebt.vscode-koverage-0.0.14/dist/extension.js:2:623567)\n\tat /home/ubuntu/.vscode-server/extensions/tenninebt.vscode-koverage-0.0.14/dist/extension.js:2:623626\n\tat new Promise (<anonymous>)\n\tat /home/ubuntu/.vscode-server/extensions/tenninebt.vscode-koverage-0.0.14/dist/extension.js:2:623507\n\tat A.xmlExtractJacoco (/home/ubuntu/.vscode-server/extensions/tenninebt.vscode-koverage-0.0.14/dist/extension.js:2:626371)\n\tat /home/ubuntu/.vscode-server/extensions/tenninebt.vscode-koverage-0.0.14/dist/extension.js:2:624051\n\tat Generator.next (<anonymous>)\n\tat j (/home/ubuntu/.vscode-server/extensions/tenninebt.vscode-koverage-0.0.14/dist/extension.js:2:623364)\n\tat s (/home/ubuntu/.vscode-server/extensions/tenninebt.vscode-koverage-0.0.14/dist/extension.js:2:623567)",
  "time": "2023-08-08T11:04:41.965Z"
}
```

**Comment by tenninebt** [comment]
Hi, sorry the very late reply. I have seen the issue and I thought I already fixed it. 
And according to the close PR #34 it seems it is. @GV94, could you confirm and close the issue if so?
Thank you

**Comment by tenninebt** [comment]
@FieteO do you have an example file for me to test and fix?
I'll try to get it done by this week-end
Thanks

**Comment by FieteO** [comment]
@tenninebt Thanks for looking into it. I will try to find something tomorrow 👍

**Comment by FieteO** [comment]
@tenninebt Here's a file that fails to be parsed with the `E.parseContent.parseContent is not a function` exception. [jacoco.xml.txt](https://github.com/tenninebt/vscode-koverage/files/12674035/jacoco.xml.txt)

I couldn't upload the xml file directly, so make sure to remove the `.txt` ending

**Comment by FieteO** [comment]
@tenninebt Did you have time to look into it?

**Comment by tenninebt** [comment]
@FieteO Had a look, I can't replicate the issue, your coverage file loads fine. Are you using the latest version of Koverage? (Can you package/zip a workspace with the coverage and some example sources that replicates it? Would help a lot. 🙏 )

@GV94 The package I'm using for Jacoco is the following : https://www.npmjs.com/package/jacoco-parse, the signature takes a callback. The issue you faced was maybe related to few missing `await`.


EDIT: I just realised that the repository is messed up. I don't understand what happened, I asked the logs from the GitHub support team, we'll see.

**Comment by FieteO** [comment]
@tenninebt I am on `v0.0.14 ` which is the latest version right? Will you be releasing a new version soon that includes your latest changes?

**Comment by FieteO** [comment]
@tenninebt Your latest release(s) fixed my issues. In `v.0.0.16` it's all working fine. I think #35 could also be relating to the same (now fixed) problem.

**Comment by tenninebt** [comment]
@FieteO Thanks but #35 is different, it is related to the content of the file. I think the parser library that I'm using fails in particular cases, but it is not maintained anymore. I will have to do the fix myself when I have time, of any "charitable soul" prepare a PR 😄
