### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by FieteO** [tenninebt/vscode-koverage#40]
As a new user, I'd like to understand what I am installing and how it is configured to do what I want.
There are two things that could be improved in the README:
- correct the description of `koverage.coverageFilePaths` (it's currently the same as `koverage.coverageFileNames`)
- better describe the Features of the extension

For the features, I'd appreciate screenshots of how it would look like to better understand what is being provided by the extension.

**Comment by amine-mf** [comment]
@FieteO Sorry for the late reply, life and work are keeping very busy ! 
I'm open to PR, if you have an idea/time to get things more clear.

**Comment by tenninebt** [comment]
@FieteO Sorry for the late reply, life and work are keeping very busy. 
I'm open to PR if you have an idea/time to get it more clear.

**Comment by tenninebt** [comment]
Had a look, the repo was in a bad state (2 years of commits were gone 😄  ). Got it fixed. (BTW the ReadMe was fine in vscode, in the extension page)
As for the screenshot, there is, if you had a look in vscode, it was also there. It is only the repository that was messed up.
