### ISSUE TITLE
Feature request: Add debounce to CoverageChanged

### ISSUE THREAD

**Issue by work933k** [tenninebt/vscode-koverage#41]
Hi!
I like this extension and have something which would improve the User Experience in certain situations.

I use Koverage in VSCode to view the level of Code Coverage of my E2E-tests for my NX-workspace. 
If i have the Koverage-explorer open and run my E2E-tests, then i see in the log the CoverageChanged event to be triggered almost every second. This seems to put quite a burden on the machine.  
Implementing some kind of debounce mechanism would probably reduce the overhead..

**Comment by tenninebt** [comment]
@work933k I understand, we'll do. (I'll get to it, hopefully, next week.) 
It will come with a better management for workspaces.
