### ISSUE TITLE
Default settings are always written to the workspace settings.json

### ISSUE THREAD

**Issue by alexisbg** [tenninebt/vscode-koverage#42]
Since Koverage 0.0.16, all its default settings are always written to the workspace settings.json:
```json
{
  "koverage.coverageCommand": "",
  "koverage.autoRefresh": true,
  "koverage.autoRefreshDebounce": 3000,
  "koverage.coverageFileNames": [
    "lcov.info",
    "cov.xml",
    "clover.xml",
    "coverage.xml",
    "jacoco.xml"
  ],
  "koverage.coverageFilePaths": [
    "**"
  ],
  "koverage.lowCoverageThreshold": 50,
  "koverage.sufficientCoverageThreshold": 70,
}
``` 
If I try to remove them, they are written again. How to avoid this behavior?

**Comment by tenninebt** [comment]
Yes, I detected right after releasing, the fix is on the way, probably today or tomorrow. Sorry for the inconvenience.

**Comment by tenninebt** [comment]
fixed by 9ba9f386dcc403c7c58e806ca31ef28b79c4dcfb 
[Release v0.0.19](https://github.com/tenninebt/vscode-koverage/releases/tag/v0.0.19)

**Comment by tenninebt** [comment]
@alexisbg Did you install the latest update? Do you confirm it is fixed?

**Comment by alexisbg** [comment]
@tenninebt Yes, Koverage has been updated to v0.0.19 on 2 projects and the issue seems to be fixed.
Merci !
