### ISSUE TITLE
Could not find a Coverage file!

### ISSUE THREAD

**Issue by polortiz4** [tenninebt/vscode-koverage#6]
Hi,

Thanks for making this nice extension!

I'm trying to use it but I can't seem to figure out how to have the extension find my lcov file. 

What's the difference between koverage.coverageFileNames and koverage.coverageFilePaths? The documentation I'm reading has them both as "coverage file names to look for". Anyhow, I currently have them both set as relative paths from the working directory to the .xml file with coverage data.

I can confirm that the filepath works elsewhere, as it is exactly the same file path I use for 
"coverage-gutters.xmlname", and the coverage-gutters highlighting is working fine.

I'm using gradle with jacoco test reports that are placed in build/reports/jacoco/test/jacocoTestReport.xml".

Here's what my settings.json file looks like: 

> {
>     "java.configuration.updateBuildConfiguration": "automatic",
>     "coverage-gutters.xmlname": "build/reports/jacoco/test/jacocoTestReport.xml",
>     "coverage-gutters.showGutterCoverage": true,
>     "koverage.coverageFileNames": [
>         "build/reports/jacoco/test/jacocoTestReport.xml",
>     ],
>     "koverage.coverageFilePaths": [
>         "build/reports/jacoco/test/jacocoTestReport.xml",
>     ],
> }

Am I doing something that's clearly wrong?

**Comment by polortiz4** [comment]
My bad, I realized like 5 seconds after making this post what the issue was.. If anyone has this confusion:

coverageFileNames is just the name of the file (without the path), and coverageFilePath is just the path to the folder with the file (not the entire path to the file)

**Comment by tenninebt** [comment]
Hey, I fix the config section in the README. It should be clearer now.
Don't hesitate if you have other issues/suggestions. I'm busy lately but I will do my best to allocate some time. Hopefully soon publish it so that more people can use it.
