### ISSUE TITLE
Files with NaN% show up as incomplete

### ISSUE THREAD

**Issue by polortiz4** [tenninebt/vscode-koverage#8]
I have some files that have no code to be covered. In my case, java interface files: they have no code that needs coverage as some just implement interfaces.
This will lead to NaN% in amount of coverage. Koverage then highlights this as incomplete coverage when, really, there is nothing we're missing in it.

Is there a way to make it so these files aren't labelled as incomplete?

**Comment by tenninebt** [comment]
It is a bit surprising that a file without statements (actually executable line of codes) is on the results of the report (Should not be listed). In any case, I have added a fix, don't know yet when I will build the next version. I will try to publish the extension once I have a fix for #7. You should be able to get the extension directly from the market place.
